abstract class Flags {
  /// Database of all flags in format : List<Map<String, String>>
  /// eg. {"name": "India", "imagePath": "in.svg"}
  static List<Map<String, String>> get list => [
        {"name": "Andorra", "imagePath": "ad.svg"},
        {"name": "United Arab Emirates", "imagePath": "ae.svg"},
        {"name": "Antigua and Barbuda", "imagePath": "ag.svg"},
        {"name": "Anguilla", "imagePath": "ai.svg"},
        {"name": "Albania", "imagePath": "al.svg"},
        {"name": "Armenia", "imagePath": "am.svg"},
        {"name": "Angola", "imagePath": "ao.svg"},
        {"name": "American Samoa", "imagePath": "as.svg"},
        {"name": "Austria", "imagePath": "at.svg"},
        {"name": "Australia", "imagePath": "au.svg"},
        {"name": "Aruba", "imagePath": "aw.svg"},
        {"name": "Åland Islands", "imagePath": "ax.svg"},
        {"name": "Azerbaijan", "imagePath": "az.svg"},
        {"name": "Bosnia and Herzegovina", "imagePath": "ba.svg"},
        {"name": "Barbados", "imagePath": "bb.svg"},
        {"name": "Bangladesh", "imagePath": "bd.svg"},
        {"name": "Belgium", "imagePath": "be.svg"},
        {"name": "Burkina Faso", "imagePath": "bf.svg"},
        {"name": "Bulgaria", "imagePath": "bg.svg"},
        {"name": "Bahrain", "imagePath": "bh.svg"},
        {"name": "Burundi", "imagePath": "bi.svg"},
        {"name": "Benin", "imagePath": "bj.svg"},
        {"name": "Saint Barthélemy", "imagePath": "bl.svg"},
        {"name": "Bermuda", "imagePath": "bm.svg"},
        {"name": "Brunei Darussalam", "imagePath": "bn.svg"},
        {"name": "Caribbean Netherlands", "imagePath": "bq.svg"},
        {"name": "Bahamas", "imagePath": "bs.svg"},
        {"name": "Bhutan", "imagePath": "bt.svg"},
        {"name": "Bouvet Island", "imagePath": "bv.svg"},
        {"name": "Botswana", "imagePath": "bw.svg"},
        {"name": "Belize", "imagePath": "bz.svg"},
        {"name": "Canada", "imagePath": "ca.svg"},
        {"name": "Cocos (Keeling) Islands", "imagePath": "cc.svg"},
        {"name": "Congo", "imagePath": "cd.svg"},
        {"name": "Central African Republic", "imagePath": "cf.svg"},
        {"name": "Republic of the Congo", "imagePath": "cg.svg"},
        {"name": "Switzerland", "imagePath": "ch.svg"},
        {"name": "Cook Islands", "imagePath": "ck.svg"},
        {"name": "Chile", "imagePath": "cl.svg"},
        {"name": "Cameroon", "imagePath": "cm.svg"},
        {"name": "Colombia", "imagePath": "co.svg"},
        {"name": "Costa Rica", "imagePath": "cr.svg"},
        {"name": "Cuba", "imagePath": "cu.svg"},
        {"name": "Cape Verde", "imagePath": "cv.svg"},
        {"name": "Curaçao", "imagePath": "cw.svg"},
        {"name": "Christmas Island", "imagePath": "cx.svg"},
        {"name": "Cyprus", "imagePath": "cy.svg"},
        {"name": "Czech Republic", "imagePath": "cz.svg"},
        {"name": "Germany", "imagePath": "de.svg"},
        {"name": "Djibouti", "imagePath": "dj.svg"},
        {"name": "Denmark", "imagePath": "dk.svg"},
        {"name": "Algeria", "imagePath": "dz.svg"},
        {"name": "Estonia", "imagePath": "ee.svg"},
        {"name": "Egypt", "imagePath": "eg.svg"},
        {"name": "Western Sahara", "imagePath": "eh.svg"},
        {"name": "Eritrea", "imagePath": "er.svg"},
        {"name": "Spain", "imagePath": "es.svg"},
        {"name": "Ethiopia", "imagePath": "et.svg"},
        {"name": "Europe", "imagePath": "eu.svg"},
        {"name": "Finland", "imagePath": "fi.svg"},
        {"name": "Fiji", "imagePath": "fj.svg"},
        {"name": "Micronesia", "imagePath": "fm.svg"},
        {"name": "Faroe Islands", "imagePath": "fo.svg"},
        {"name": "France", "imagePath": "fr.svg"},
        {"name": "Gabon", "imagePath": "ga.svg"},
        {"name": "England", "imagePath": "gb-eng.svg"},
        {"name": "Northern Ireland", "imagePath": "gb-nir.svg"},
        {"name": "Wales", "imagePath": "gb-wls.svg"},
        {"name": "United Kingdom", "imagePath": "gb.svg"},
        {"name": "Grenada", "imagePath": "gd.svg"},
        {"name": "Georgia", "imagePath": "ge.svg"},
        {"name": "French Guiana", "imagePath": "gf.svg"},
        {"name": "Guernsey", "imagePath": "gg.svg"},
        {"name": "Ghana", "imagePath": "gh.svg"},
        {"name": "Gibraltar", "imagePath": "gi.svg"},
        {"name": "Greenland", "imagePath": "gl.svg"},
        {"name": "Gambia", "imagePath": "gm.svg"},
        {"name": "Guinea", "imagePath": "gn.svg"},
        {"name": "Guadeloupe", "imagePath": "gp.svg"},
        {"name": "Equatorial Guinea", "imagePath": "gq.svg"},
        {"name": "Greece", "imagePath": "gr.svg"},
        {"name": "Guatemala", "imagePath": "gt.svg"},
        {"name": "Guam", "imagePath": "gu.svg"},
        {"name": "Guinea-Bissau", "imagePath": "gw.svg"},
        {"name": "Guyana", "imagePath": "gy.svg"},
        {"name": "Hong Kong", "imagePath": "hk.svg"},
        {"name": "Heard Island and McDonald Islands", "imagePath": "hm.svg"},
        {"name": "Honduras", "imagePath": "hn.svg"},
        {"name": "Croatia", "imagePath": "hr.svg"},
        {"name": "Haiti", "imagePath": "ht.svg"},
        {"name": "Hungary", "imagePath": "hu.svg"},
        {"name": "Indonesia", "imagePath": "id.svg"},
        {"name": "Ireland", "imagePath": "ie.svg"},
        {"name": "Israel", "imagePath": "il.svg"},
        {"name": "Isle of Man", "imagePath": "im.svg"},
        {"name": "India", "imagePath": "in.svg"},
        {"name": "British Indian Ocean Territory", "imagePath": "io.svg"},
        {"name": "Iraq", "imagePath": "iq.svg"},
        {"name": "Iran, Islamic Republic of", "imagePath": "ir.svg"},
        {"name": "Iceland", "imagePath": "is.svg"},
        {"name": "Italy", "imagePath": "it.svg"},
        {"name": "Jersey", "imagePath": "je.svg"},
        {"name": "Jamaica", "imagePath": "jm.svg"},
        {"name": "Jordan", "imagePath": "jo.svg"},
        {"name": "Japan", "imagePath": "jp.svg"},
        {"name": "Kenya", "imagePath": "ke.svg"},
        {"name": "Kyrgyzstan", "imagePath": "kg.svg"},
        {"name": "Cambodia", "imagePath": "kh.svg"},
        {"name": "Comoros", "imagePath": "km.svg"},
        {"name": "Saint Kitts and Nevis", "imagePath": "kn.svg"},
        {"name": "Korea", "imagePath": "kp.svg"},
        {"name": "Korea, Republic of", "imagePath": "kr.svg"},
        {"name": "Kuwait", "imagePath": "kw.svg"},
        {"name": "Kazakhstan", "imagePath": "kz.svg"},
        {"name": "Laos", "imagePath": "la.svg"},
        {"name": "Lebanon", "imagePath": "lb.svg"},
        {"name": "Saint Lucia", "imagePath": "lc.svg"},
        {"name": "Liechtenstein", "imagePath": "li.svg"},
        {"name": "Liberia", "imagePath": "lr.svg"},
        {"name": "Lesotho", "imagePath": "ls.svg"},
        {"name": "Lithuania", "imagePath": "lt.svg"},
        {"name": "Luxembourg", "imagePath": "lu.svg"},
        {"name": "Latvia", "imagePath": "lv.svg"},
        {"name": "Libya", "imagePath": "ly.svg"},
        {"name": "Morocco", "imagePath": "ma.svg"},
        {"name": "Monaco", "imagePath": "mc.svg"},
        {"name": "Moldova, Republic of", "imagePath": "md.svg"},
        {"name": "Montenegro", "imagePath": "me.svg"},
        {"name": "Saint Martin", "imagePath": "mf.svg"},
        {"name": "Madagascar", "imagePath": "mg.svg"},
        {"name": "Marshall Islands", "imagePath": "mh.svg"},
        {"name": "North Macedonia", "imagePath": "mk.svg"},
        {"name": "Mali", "imagePath": "ml.svg"},
        {"name": "Myanmar", "imagePath": "mm.svg"},
        {"name": "Mongolia", "imagePath": "mn.svg"},
        {"name": "Macao", "imagePath": "mo.svg"},
        {"name": "Martinique", "imagePath": "mq.svg"},
        {"name": "Mauritania", "imagePath": "mr.svg"},
        {"name": "Montserrat", "imagePath": "ms.svg"},
        {"name": "Malta", "imagePath": "mt.svg"},
        {"name": "Mauritius", "imagePath": "mu.svg"},
        {"name": "Maldives", "imagePath": "mv.svg"},
        {"name": "Malawi", "imagePath": "mw.svg"},
        {"name": "Malaysia", "imagePath": "my.svg"},
        {"name": "Mozambique", "imagePath": "mz.svg"},
        {"name": "Namibia", "imagePath": "na.svg"},
        {"name": "New Caledonia", "imagePath": "nc.svg"},
        {"name": "Niger", "imagePath": "ne.svg"},
        {"name": "Norfolk Island", "imagePath": "nf.svg"},
        {"name": "Nigeria", "imagePath": "ng.svg"},
        {"name": "Nicaragua", "imagePath": "ni.svg"},
        {"name": "Netherlands", "imagePath": "nl.svg"},
        {"name": "Norway", "imagePath": "no.svg"},
        {"name": "Nauru", "imagePath": "nr.svg"},
        {"name": "Niue", "imagePath": "nu.svg"},
        {"name": "New Zealand", "imagePath": "nz.svg"},
        {"name": "Oman", "imagePath": "om.svg"},
        {"name": "Panama", "imagePath": "pa.svg"},
        {"name": "French Polynesia", "imagePath": "pf.svg"},
        {"name": "Papua New Guinea", "imagePath": "pg.svg"},
        {"name": "Philippines", "imagePath": "ph.svg"},
        {"name": "Pakistan", "imagePath": "pk.svg"},
        {"name": "Poland", "imagePath": "pl.svg"},
        {"name": "Saint Pierre and Miquelon", "imagePath": "pm.svg"},
        {"name": "Pitcairn", "imagePath": "pn.svg"},
        {"name": "Puerto Rico", "imagePath": "pr.svg"},
        {"name": "Palestine", "imagePath": "ps.svg"},
        {"name": "Portugal", "imagePath": "pt.svg"},
        {"name": "Palau", "imagePath": "pw.svg"},
        {"name": "Paraguay", "imagePath": "py.svg"},
        {"name": "Qatar", "imagePath": "qa.svg"},
        {"name": "Réunion", "imagePath": "re.svg"},
        {"name": "Romania", "imagePath": "ro.svg"},
        {"name": "Serbia", "imagePath": "rs.svg"},
        {"name": "Russian Federation", "imagePath": "ru.svg"},
        {"name": "Rwanda", "imagePath": "rw.svg"},
        {"name": "Saudi Arabia", "imagePath": "sa.svg"},
        {"name": "Solomon Islands", "imagePath": "sb.svg"},
        {"name": "Seychelles", "imagePath": "sc.svg"},
        {"name": "Sudan", "imagePath": "sd.svg"},
        {"name": "Sweden", "imagePath": "se.svg"},
        {"name": "Singapore", "imagePath": "sg.svg"},
        {
          "name": "Saint Helena, Ascension and Tristan da Cunha",
          "imagePath": "sh.svg"
        },
        {"name": "Slovenia", "imagePath": "si.svg"},
        {"name": "Svalbard and Jan Mayen Islands", "imagePath": "sj.svg"},
        {"name": "Slovakia", "imagePath": "sk.svg"},
        {"name": "Sierra Leone", "imagePath": "sl.svg"},
        {"name": "San Marino", "imagePath": "sm.svg"},
        {"name": "Senegal", "imagePath": "sn.svg"},
        {"name": "Somalia", "imagePath": "so.svg"},
        {"name": "Suriname", "imagePath": "sr.svg"},
        {"name": "South Sudan", "imagePath": "ss.svg"},
        {"name": "Sao Tome and Principe", "imagePath": "st.svg"},
        {"name": "Sint Maarten", "imagePath": "sx.svg"},
        {"name": "Syrian Arab Republic", "imagePath": "sy.svg"},
        {"name": "Swaziland", "imagePath": "sz.svg"},
        {"name": "Chad", "imagePath": "td.svg"},
        {"name": "French Southern Territories", "imagePath": "tf.svg"},
        {"name": "Togo", "imagePath": "tg.svg"},
        {"name": "Thailand", "imagePath": "th.svg"},
        {"name": "Tajikistan", "imagePath": "tj.svg"},
        {"name": "Tokelau", "imagePath": "tk.svg"},
        {"name": "Timor-Leste", "imagePath": "tl.svg"},
        {"name": "Turkmenistan", "imagePath": "tm.svg"},
        {"name": "Tunisia", "imagePath": "tn.svg"},
        {"name": "Tonga", "imagePath": "to.svg"},
        {"name": "Turkey", "imagePath": "tr.svg"},
        {"name": "Trinidad and Tobago", "imagePath": "tt.svg"},
        {"name": "Tuvalu", "imagePath": "tv.svg"},
        {"name": "Taiwan (Republic of China)", "imagePath": "tw.svg"},
        {"name": "Tanzania, United Republic of", "imagePath": "tz.svg"},
        {"name": "Ukraine", "imagePath": "ua.svg"},
        {"name": "Uganda", "imagePath": "ug.svg"},
        {"name": "US Minor Outlying Islands", "imagePath": "um.svg"},
        {"name": "United States", "imagePath": "us.svg"},
        {"name": "Uruguay", "imagePath": "uy.svg"},
        {"name": "Uzbekistan", "imagePath": "uz.svg"},
        {"name": "Holy See", "imagePath": "va.svg"},
        {"name": "Saint Vincent and the Grenadines", "imagePath": "vc.svg"},
        {"name": "Venezuela", "imagePath": "ve.svg"},
        {"name": "Virgin Islands, British", "imagePath": "vg.svg"},
        {"name": "Virgin Islands, U.S.", "imagePath": "vi.svg"},
        {"name": "Vietnam", "imagePath": "vn.svg"},
        {"name": "Vanuatu", "imagePath": "vu.svg"},
        {"name": "Samoa", "imagePath": "ws.svg"},
        {"name": "Kosovo", "imagePath": "xk.svg"},
        {"name": "Yemen", "imagePath": "ye.svg"},
        {"name": "Mayotte", "imagePath": "yt.svg"},
        {"name": "Zambia", "imagePath": "zm.svg"},
        {"name": "Zimbabwe", "imagePath": "zw.svg"}
      ];
}
